services:
  order-db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - inventory-data:/var/lib/postgresql/data

  notification-db:
    image: postgres:15
    container_name: notification_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: notification_db
    ports:
      - "5434:5432"
    volumes:
      - notification-data:/var/lib/postgresql/data

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  order-data:
  inventory-data:
  notification-data:
  kafka-data: