<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.7</version>
        <relativePath/>
    </parent>

    <groupId>org.onlinestore</groupId>
    <artifactId>onlinestore</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>
    <name>Common Library for OnlineStore</name>

    <modules>
        <module>OrderService</module>
        <module>NotificationService</module>
        <module>InventoryService</module>
        <module>common-lib</module>
    </modules>

    <properties>
        <spring.boot.version>3.5.7</spring.boot.version>
        <java.version>17</java.version>
        <grpc.version>1.76.0</grpc.version>
        <protobuf-java.version>4.31.1</protobuf-java.version>
        <flyway.version>11.13.2</flyway.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <h2database.version>2.4.240</h2database.version>
        <lombok.version>1.18.32</lombok.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
